export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_JS = 'SHOW_JS'
export const SHOW_HTML = 'SHOW_HTML'
export const SHOW_CSS = 'SHOW_CSS'
export const SHOW_ESS = 'SHOW_ESS'
export const SHOW_PIC = 'SHOW_PIC'